export enum COLOR_CODES_FOR_LIGHT_THEME {
  PRIMARY = '#FFFFFF',
  SECONDARY = '#F5F6FA'
}

export enum COLOR_CODES_FOR_DARK_THEME {
  PRIMARY = '#2F3542',
  SECONDARY = '#2C2C54'
}

export enum PADDINGS {
  SMALL = 8,
  LARGE = 16,
  X_SMALL = 4,
  MEDIUM = 12,
  X_LARGE = 24,
}
