export enum COLOR_CODES_FOR_LIGHT_THEME {
  PRIMARY = '#FFFFFF',
  SECONDARY = '#F5F6FA',
  SHADOW = '#2F3542',
}

export enum COLOR_CODES_FOR_DARK_THEME {
  PRIMARY = '#2F3542',
  SECONDARY = '#2C2C54',
  SHADOW = '#F5F6FA',
}

export enum PADDINGS {
  SMALL = 8,
  LARGE = 16,
  X_SMALL = 4,
  MEDIUM = 12,
  X_LARGE = 24,
}

export enum IMAGE_DIMENSIONS {
  SMALL = 18,
  LARGE = 32,
  MEDIUM = 28,
  REGULAR = 24,
  X_SMALL = 14,
  XX_SMALL = 12,
}
