export enum COLOR_CODES_FOR_LIGHT_THEME {
  PRIMARY = '#FFFFFF',
  SECONDARY = '#F5F6FA',
  SHADOW = '#2F3542',
  OUTLINE = '#000000',
}

export enum COLOR_CODES_FOR_DARK_THEME {
  PRIMARY = '#2F3542',
  SECONDARY = '#2C2C54',
  SHADOW = '#B2BEC3',
  OUTLINE = '#FFFFFF',
}

export enum PADDINGS {
  SMALL = 8,
  LARGE = 16,
  X_SMALL = 4,
  MEDIUM = 12,
  X_LARGE = 24,
}

export enum IMAGE_DIMENSIONS {
  SMALL = 18,
  LARGE = 32,
  MEDIUM = 28,
  REGULAR = 24,
  X_SMALL = 14,
  XX_SMALL = 12,
}

export enum INPUT_TYPE {
  OUTLINE = 'OUTLINE',
  UNDERLINE = 'UNDERLINE',
  FLOATING_LABEL = 'FLOATING_LABEL'
}

export enum COLUMN_ALIGNMENT {
  START = 'START',
  CENTER = 'CENTER'
}
